#!/usr/bin/env python3
"""Merge en_us.json keys into locale files; apply locale-specific overrides."""
import json
from pathlib import Path

LANG_DIR = Path(__file__).resolve().parents[1] / "src/main/resources/assets/take-your-stream-chat/lang"

# Keys added or updated for 2.0.x — locale-specific strings (en_us is fallback).
OVERRIDES: dict[str, dict[str, str]] = {
    "de_de": {
        "takeyourstreamchat.config.hint_default": "Bewege die Maus über eine Einstellung für die Beschreibung",
        "takeyourstreamchat.config.message_history_max": "Verlaufsgröße",
        "takeyourstreamchat.config.message_history_max.desc": "Maximale Anzahl gespeicherter Chat-Nachrichten",
        "takeyourstreamchat.config.spawn_min_distance": "Min. Spawn-Entfernung (Blöcke):",
        "takeyourstreamchat.config.spawn_max_distance": "Max. Spawn-Entfernung (Blöcke):",
        "takeyourstreamchat.config.spawn_min_distance.desc": "Minimale horizontale Entfernung für „Um den Spieler“ und FOP (Blöcke)",
        "takeyourstreamchat.config.spawn_max_distance.desc": "Maximale horizontale Entfernung für „Um den Spieler“ und FOP (Blöcke)",
        "takeyourstreamchat.config.regexps": "Regexps",
        "takeyourstreamchat.config.regexps.desc": "Regex-Verwaltung öffnen",
        "takeyourstreamchat.config.regexps_config": "Konfig",
        "takeyourstreamchat.config.role_filter": "Rollenfilter:",
        "takeyourstreamchat.config.role_filter.desc": "Nachrichten nur von ausgewählten Rollen auf allen Plattformen (Twitch, YouTube, Kick, TikTok). Bei „Alle“ auch normale Zuschauer.",
        "takeyourstreamchat.config.role_filter.all": "Alle",
        "takeyourstreamchat.config.role_filter.subscribers": "Abonnenten",
        "takeyourstreamchat.config.role_filter.vip": "VIP",
        "takeyourstreamchat.config.role_filter.mods": "Mods",
        "takeyourstreamchat.config.role_filter.sub_or_vip": "Sub oder VIP",
        "takeyourstreamchat.config.role_filter.sub_or_mod": "Sub oder Mod",
        "takeyourstreamchat.config.username_blocklist": "Nutzer-Sperrliste:",
        "takeyourstreamchat.config.username_blocklist.desc": "Nachrichten bestimmter Nutzer blockieren",
        "takeyourstreamchat.config.blocked_users": "Gesperrte Nutzer",
        "takeyourstreamchat.config.blocked_users.desc": "Verwaltung der gesperrten Nutzernamen",
        "takeyourstreamchat.config.blocked_users_config": "Konfig",
        "takeyourstreamchat.blocked_users.title": "Gesperrte Nutzernamen",
        "takeyourstreamchat.blocked_users.input": "Nutzername eingeben",
        "takeyourstreamchat.blocked_users.add": "Hinzufügen",
        "takeyourstreamchat.regexps.title": "Regex-Verwaltung",
        "takeyourstreamchat.config.twitch_enabled": "Twitch:",
        "takeyourstreamchat.config.twitch_enabled.desc": "Twitch-Chat beim Verbinden einschließen",
        "takeyourstreamchat.config.youtube_enabled": "YouTube:",
        "takeyourstreamchat.config.youtube_enabled.desc": "YouTube-Livechat beim Verbinden einschließen",
        "takeyourstreamchat.config.youtube_channel": "YouTube-Kanal:",
        "takeyourstreamchat.config.youtube_channel.desc": "YouTube @Handle, Video-URL oder 11-stellige Video-ID während des Streams. ON/OFF rechts schaltet die Plattform ein.",
        "takeyourstreamchat.config.kick_enabled": "Kick:",
        "takeyourstreamchat.config.kick_enabled.desc": "Kick-Chat beim Verbinden einschließen",
        "takeyourstreamchat.config.kick_channel": "Kick-Kanal:",
        "takeyourstreamchat.config.kick_channel.desc": "Kick-Kanal-Slug von kick.com/username. ON/OFF rechts schaltet die Plattform ein.",
        "takeyourstreamchat.config.tiktok_enabled": "TikTok:",
        "takeyourstreamchat.config.tiktok_enabled.desc": "TikTok-Livechat beim Verbinden einschließen",
        "takeyourstreamchat.config.tiktok_username": "TikTok-Benutzername:",
        "takeyourstreamchat.config.tiktok_username.desc": "TikTok @username während des Livestreams. ON/OFF rechts schaltet die Plattform ein.",
        "takeyourstreamchat.config.chat_connection": "Live-Chat:",
        "takeyourstreamchat.config.chat_connection.desc": "Alle aktivierten Plattformen verbinden oder trennen (wie Hotkey)",
        "takeyourstreamchat.config.chat_toggle_on": "Chat AN",
        "takeyourstreamchat.config.chat_toggle_off": "Chat AUS",
        "takeyourstreamchat.config.auto_connect_irc": "Auto-Verbinden beim Betreten:",
        "takeyourstreamchat.config.auto_connect_irc.desc": "Beim Betreten einer Welt/des Servers automatisch verbinden",
        "takeyourstreamchat.config.message_lifetime.desc": "Sichtbarkeitsdauer der Nachrichten (in Ticks)",
        "takeyourstreamchat.config.message_fall.desc": "Fallzeit der Nachrichten (in Ticks)",
        "takeyourstreamchat.config.message_sound": "Ton bei neuer Nachricht:",
        "takeyourstreamchat.config.message_sound.desc": "Benachrichtigungston bei neuer Chat-Nachricht",
        "takeyourstreamchat.config.message_sound_volume": "Benachrichtigungslautstärke (0–1):",
        "takeyourstreamchat.config.message_sound_volume.desc": "Lautstärke des Benachrichtigungstons",
        "takeyourstreamchat.config.color_emojis": "Farbige Emojis:",
        "takeyourstreamchat.config.color_emojis.desc": "Unicode-Emojis mit System-Emoji-Schrift statt Minecraft-Schrift rendern",
        "takeyourstreamchat.config.click_to_remove": "Klick zum Entfernen:",
        "takeyourstreamchat.config.click_to_remove.desc": "Linksklick entfernt Nachrichten sofort (mit Partikeln)",
        "takeyourstreamchat.config.unpin_mode": "Loslösen:",
        "takeyourstreamchat.config.unpin_mode.desc": "Angeheftete 3D-Nachricht mit Rechtsklick loslösen. „Ganze Nachricht“: kurzer Klick löst, Halten zieht",
        "takeyourstreamchat.config.unpin_mode.pin_icon": "Nur Pin-Symbol",
        "takeyourstreamchat.config.unpin_mode.whole_message": "Ganze Nachricht",
        "takeyourstreamchat.status.connecting": "Verbinden mit %s: %s...",
        "takeyourstreamchat.status.connected_count": "Verbunden: %s Plattform(en)",
        "takeyourstreamchat.status.no_platforms": "Keine Plattformen in den Einstellungen aktiviert",
        "takeyourstreamchat.status.disconnected": "Chat getrennt",
        "takeyourstreamchat.status.not_connected": "Nicht mit Chat verbunden",
        "takeyourstreamchat.status.offline_one": "%s: %s — offline",
        "takeyourstreamchat.status.offline_platform": "%s — offline",
        "takeyourstreamchat.status.offline_many": "Offline: %s",
        "takeyourstreamchat.status.offline_count": "Offline-Plattformen: %s",
        "takeyourstreamchat.chat.connecting": "Verbinden mit %s-Chat '%s'...",
        "takeyourstreamchat.chat.connected_count": "Mit %s Chat-Plattform(en) verbunden!",
        "takeyourstreamchat.chat.no_platforms": "Keine Plattformen aktiviert. Mindestens eine in den Einstellungen einschalten.",
        "takeyourstreamchat.chat.disconnected": "Von allen Chat-Plattformen getrennt.",
        "takeyourstreamchat.chat.not_connected": "Mit keiner Chat-Plattform verbunden.",
        "takeyourstreamchat.chat.error.connect": "Verbindungsfehler zu %s: %s",
        "takeyourstreamchat.chat.error.generic": "%s-Verbindungsfehler: %s",
        "takeyourstreamchat.chat.error.not_live": "%s: '%s' ist gerade nicht live",
        "takeyourstreamchat.chat.error.no_live_room": "%s: kein Livestream für '%s' (falscher Name oder offline)",
        "takeyourstreamchat.chat.error.no_live_chat": "%s: Live-Chat für '%s' nicht verfügbar",
        "takeyourstreamchat.chat.error.user_not_found": "%s: Kanal '%s' nicht gefunden",
        "takeyourstreamchat.chat.error.blocked": "%s: Anfrage von der Plattform blockiert, erneuter Versuch...",
        "takeyourstreamchat.history.count": "Nachrichten im Verlauf: %s",
        "takeyourstreamchat.history.pinned_count": "Angeheftet: %s",
        "takeyourstreamchat.history.pinned_empty": "Keine angehefteten Nachrichten. Hefte in der Welt oder im Verlauf an.",
        "takeyourstreamchat.history.empty": "Noch keine Nachrichten. Verbinde einen Chat, um sie hier zu sehen.",
        "takeyourstreamchat.history.scroll_hint": "Scrollen · Klick für Aktionen",
        "takeyourstreamchat.history.click_for_actions": "Anheften, blockieren oder wiederholen",
        "takeyourstreamchat.history.action.pin": "Anheften",
        "takeyourstreamchat.history.action.unpin": "Loslösen",
        "takeyourstreamchat.history.action.block": "Nutzer blockieren",
        "takeyourstreamchat.history.action.replay": "In der Welt wiederholen",
        "takeyourstreamchat.history.message_pinned": "Nachricht angeheftet",
        "takeyourstreamchat.history.message_unpinned": "Nachricht gelöst",
        "takeyourstreamchat.history.message_replayed": "Nachricht in der Welt wiederholt",
        "takeyourstreamchat.history.user_blocked": "%s wurde blockiert",
        "takeyourstreamchat.history.user_already_blocked": "%s ist bereits blockiert",
        "takeyourstreamchat.history.blocked_badge": "[gesperrt]",
        "key.takeyourstreamchat.startandstop": "Chat verbinden / trennen",
    },
    "fr_fr": {
        "takeyourstreamchat.config.title": "Paramètres Stream Chat",
        "takeyourstreamchat.config.hint_default": "Survolez un paramètre pour voir sa description",
        "takeyourstreamchat.config.message_history_max": "Taille de l'historique",
        "takeyourstreamchat.config.message_history_max.desc": "Nombre maximum de messages conservés",
        "takeyourstreamchat.config.spawn_min_distance": "Distance min. d'apparition (blocs) :",
        "takeyourstreamchat.config.spawn_max_distance": "Distance max. d'apparition (blocs) :",
        "takeyourstreamchat.config.spawn_min_distance.desc": "Distance horizontale minimale pour « Autour du joueur » et FOP (blocs)",
        "takeyourstreamchat.config.spawn_max_distance.desc": "Distance horizontale maximale pour « Autour du joueur » et FOP (blocs)",
        "takeyourstreamchat.config.regexps": "Regexps",
        "takeyourstreamchat.config.regexps.desc": "Ouvrir la gestion des regex",
        "takeyourstreamchat.config.regexps_config": "Config",
        "takeyourstreamchat.config.role_filter": "Filtre de rôles :",
        "takeyourstreamchat.config.role_filter.desc": "Afficher les messages des rôles sélectionnés sur toutes les plateformes. Les viewers normaux passent avec « Tous ».",
        "takeyourstreamchat.config.role_filter.all": "Tous",
        "takeyourstreamchat.config.role_filter.subscribers": "Abonnés",
        "takeyourstreamchat.config.role_filter.vip": "VIP",
        "takeyourstreamchat.config.role_filter.mods": "Mods",
        "takeyourstreamchat.config.role_filter.sub_or_vip": "Sub ou VIP",
        "takeyourstreamchat.config.role_filter.sub_or_mod": "Sub ou mod",
        "takeyourstreamchat.config.username_blocklist": "Liste de blocage :",
        "takeyourstreamchat.config.username_blocklist.desc": "Bloquer les messages de certains pseudos",
        "takeyourstreamchat.config.blocked_users": "Utilisateurs bloqués",
        "takeyourstreamchat.config.blocked_users.desc": "Gérer les pseudos bloqués",
        "takeyourstreamchat.config.blocked_users_config": "Config",
        "takeyourstreamchat.blocked_users.title": "Pseudos bloqués",
        "takeyourstreamchat.blocked_users.input": "Entrer un pseudo",
        "takeyourstreamchat.blocked_users.add": "Ajouter",
        "takeyourstreamchat.regexps.title": "Gestion des regex",
        "takeyourstreamchat.config.twitch_enabled": "Twitch :",
        "takeyourstreamchat.config.twitch_enabled.desc": "Inclure le chat Twitch lors de la connexion",
        "takeyourstreamchat.config.youtube_enabled": "YouTube :",
        "takeyourstreamchat.config.youtube_enabled.desc": "Inclure le chat live YouTube lors de la connexion",
        "takeyourstreamchat.config.youtube_channel": "Chaîne YouTube :",
        "takeyourstreamchat.config.youtube_channel.desc": "@handle, URL vidéo ou ID vidéo (11 car.) en direct. ON/OFF à droite active la plateforme.",
        "takeyourstreamchat.config.kick_enabled": "Kick :",
        "takeyourstreamchat.config.kick_enabled.desc": "Inclure le chat Kick lors de la connexion",
        "takeyourstreamchat.config.kick_channel": "Chaîne Kick :",
        "takeyourstreamchat.config.kick_channel.desc": "Slug Kick depuis kick.com/username. ON/OFF à droite active la plateforme.",
        "takeyourstreamchat.config.tiktok_enabled": "TikTok :",
        "takeyourstreamchat.config.tiktok_enabled.desc": "Inclure le chat live TikTok lors de la connexion",
        "takeyourstreamchat.config.tiktok_username": "Pseudo TikTok :",
        "takeyourstreamchat.config.tiktok_username.desc": "@username TikTok en direct. ON/OFF à droite active la plateforme.",
        "takeyourstreamchat.config.chat_connection": "Chat live :",
        "takeyourstreamchat.config.chat_connection.desc": "Connecter ou déconnecter toutes les plateformes activées (comme le raccourci)",
        "takeyourstreamchat.config.chat_toggle_on": "Chat ON",
        "takeyourstreamchat.config.chat_toggle_off": "Chat OFF",
        "takeyourstreamchat.config.auto_connect_irc": "Connexion auto à l'entrée :",
        "takeyourstreamchat.config.auto_connect_irc.desc": "Se connecter automatiquement en entrant dans un monde/serveur",
        "takeyourstreamchat.config.message_lifetime.desc": "Durée d'affichage des messages (en ticks)",
        "takeyourstreamchat.config.message_fall.desc": "Durée de chute des messages (en ticks)",
        "takeyourstreamchat.config.message_sound": "Son des nouveaux messages :",
        "takeyourstreamchat.config.message_sound.desc": "Jouer un son à l'arrivée d'un message",
        "takeyourstreamchat.config.message_sound_volume": "Volume des notifications (0–1) :",
        "takeyourstreamchat.config.message_sound_volume.desc": "Volume du son de notification",
        "takeyourstreamchat.config.color_emojis": "Emojis couleur :",
        "takeyourstreamchat.config.color_emojis.desc": "Afficher les emojis Unicode avec la police système au lieu de Minecraft",
        "takeyourstreamchat.config.click_to_remove": "Clic pour supprimer :",
        "takeyourstreamchat.config.click_to_remove.desc": "Clic gauche pour supprimer un message avec des particules",
        "takeyourstreamchat.config.unpin_mode": "Désépingler :",
        "takeyourstreamchat.config.unpin_mode.desc": "Désépingler un message 3D avec clic droit. « Message entier » : clic court désépingle, maintien déplace",
        "takeyourstreamchat.config.unpin_mode.pin_icon": "Icône d'épingle seulement",
        "takeyourstreamchat.config.unpin_mode.whole_message": "Message entier",
        "takeyourstreamchat.status.connecting": "Connexion à %s : %s...",
        "takeyourstreamchat.status.connected_count": "Connecté : %s plateforme(s)",
        "takeyourstreamchat.status.no_platforms": "Aucune plateforme activée dans les paramètres",
        "takeyourstreamchat.status.disconnected": "Chat déconnecté",
        "takeyourstreamchat.status.not_connected": "Non connecté au chat",
        "takeyourstreamchat.status.offline_one": "%s : %s — hors ligne",
        "takeyourstreamchat.status.offline_platform": "%s — hors ligne",
        "takeyourstreamchat.status.offline_many": "Hors ligne : %s",
        "takeyourstreamchat.status.offline_count": "Plateformes hors ligne : %s",
        "takeyourstreamchat.chat.connecting": "Connexion au chat %s '%s'...",
        "takeyourstreamchat.chat.connected_count": "Connecté à %s plateforme(s) de chat !",
        "takeyourstreamchat.chat.no_platforms": "Aucune plateforme activée. Activez-en au moins une.",
        "takeyourstreamchat.chat.disconnected": "Déconnecté de toutes les plateformes.",
        "takeyourstreamchat.chat.not_connected": "Non connecté à une plateforme de chat.",
        "takeyourstreamchat.chat.error.connect": "Erreur de connexion à %s : %s",
        "takeyourstreamchat.chat.error.generic": "Erreur de connexion %s : %s",
        "takeyourstreamchat.chat.error.not_live": "%s : '%s' n'est pas en direct",
        "takeyourstreamchat.chat.error.no_live_room": "%s : aucun direct pour '%s' (nom incorrect ou hors ligne)",
        "takeyourstreamchat.chat.error.no_live_chat": "%s : chat live indisponible pour '%s'",
        "takeyourstreamchat.chat.error.user_not_found": "%s : chaîne '%s' introuvable",
        "takeyourstreamchat.chat.error.blocked": "%s : requête bloquée par la plateforme, nouvel essai...",
        "takeyourstreamchat.history.count": "Messages dans l'historique : %s",
        "takeyourstreamchat.history.pinned_count": "Épinglés : %s",
        "takeyourstreamchat.history.pinned_empty": "Aucun message épinglé. Épinglez-en un dans le monde ou l'historique.",
        "takeyourstreamchat.history.empty": "Pas encore de messages. Connectez un chat pour les voir ici.",
        "takeyourstreamchat.history.scroll_hint": "Défiler · Clic pour les actions",
        "takeyourstreamchat.history.click_for_actions": "Épingler, bloquer ou rejouer",
        "takeyourstreamchat.history.action.pin": "Épingler",
        "takeyourstreamchat.history.action.unpin": "Désépingler",
        "takeyourstreamchat.history.action.block": "Bloquer l'utilisateur",
        "takeyourstreamchat.history.action.replay": "Rejouer dans le monde",
        "takeyourstreamchat.history.message_pinned": "Message épinglé",
        "takeyourstreamchat.history.message_unpinned": "Message désépinglé",
        "takeyourstreamchat.history.message_replayed": "Message rejoué dans le monde",
        "takeyourstreamchat.history.user_blocked": "%s a été bloqué",
        "takeyourstreamchat.history.user_already_blocked": "%s est déjà bloqué",
        "takeyourstreamchat.history.blocked_badge": "[bloqué]",
        "key.takeyourstreamchat.openconfig": "Ouvrir les paramètres Stream Chat",
        "key.takeyourstreamchat.startandstop": "Connecter / déconnecter le chat",
    },
    "es_es": {
        "takeyourstreamchat.config.title": "Ajustes de Stream Chat",
        "takeyourstreamchat.config.hint_default": "Pasa el cursor sobre un ajuste para ver su descripción",
        "takeyourstreamchat.config.message_history_max": "Tamaño del historial",
        "takeyourstreamchat.config.message_history_max.desc": "Número máximo de mensajes guardados",
        "takeyourstreamchat.config.spawn_min_distance": "Distancia mín. de aparición (bloques):",
        "takeyourstreamchat.config.spawn_max_distance": "Distancia máx. de aparición (bloques):",
        "takeyourstreamchat.config.spawn_min_distance.desc": "Distancia horizontal mínima para «Alrededor del jugador» y FOP (bloques)",
        "takeyourstreamchat.config.spawn_max_distance.desc": "Distancia horizontal máxima para «Alrededor del jugador» y FOP (bloques)",
        "takeyourstreamchat.config.regexps": "Regexps",
        "takeyourstreamchat.config.regexps.desc": "Abrir gestión de regex",
        "takeyourstreamchat.config.regexps_config": "Config",
        "takeyourstreamchat.config.role_filter": "Filtro de roles:",
        "takeyourstreamchat.config.role_filter.desc": "Mostrar mensajes solo de roles seleccionados en todas las plataformas. Con «Todos» también pasan viewers normales.",
        "takeyourstreamchat.config.role_filter.all": "Todos",
        "takeyourstreamchat.config.role_filter.subscribers": "Suscriptores",
        "takeyourstreamchat.config.role_filter.vip": "VIP",
        "takeyourstreamchat.config.role_filter.mods": "Mods",
        "takeyourstreamchat.config.role_filter.sub_or_vip": "Sub o VIP",
        "takeyourstreamchat.config.role_filter.sub_or_mod": "Sub o mod",
        "takeyourstreamchat.config.username_blocklist": "Lista de bloqueo:",
        "takeyourstreamchat.config.username_blocklist.desc": "Bloquear mensajes de ciertos usuarios",
        "takeyourstreamchat.config.blocked_users": "Usuarios bloqueados",
        "takeyourstreamchat.config.blocked_users.desc": "Gestionar nombres bloqueados",
        "takeyourstreamchat.config.blocked_users_config": "Config",
        "takeyourstreamchat.blocked_users.title": "Nombres bloqueados",
        "takeyourstreamchat.blocked_users.input": "Introducir nombre",
        "takeyourstreamchat.blocked_users.add": "Añadir",
        "takeyourstreamchat.regexps.title": "Gestión de regex",
        "takeyourstreamchat.config.twitch_enabled": "Twitch:",
        "takeyourstreamchat.config.twitch_enabled.desc": "Incluir chat de Twitch al conectar",
        "takeyourstreamchat.config.youtube_enabled": "YouTube:",
        "takeyourstreamchat.config.youtube_enabled.desc": "Incluir chat en vivo de YouTube al conectar",
        "takeyourstreamchat.config.youtube_channel": "Canal de YouTube:",
        "takeyourstreamchat.config.youtube_channel.desc": "@handle, URL de vídeo o ID de 11 caracteres en directo. ON/OFF a la derecha activa la plataforma.",
        "takeyourstreamchat.config.kick_enabled": "Kick:",
        "takeyourstreamchat.config.kick_enabled.desc": "Incluir chat de Kick al conectar",
        "takeyourstreamchat.config.kick_channel": "Canal de Kick:",
        "takeyourstreamchat.config.kick_channel.desc": "Slug de kick.com/username. ON/OFF a la derecha activa la plataforma.",
        "takeyourstreamchat.config.tiktok_enabled": "TikTok:",
        "takeyourstreamchat.config.tiktok_enabled.desc": "Incluir chat en vivo de TikTok al conectar",
        "takeyourstreamchat.config.tiktok_username": "Usuario de TikTok:",
        "takeyourstreamchat.config.tiktok_username.desc": "@username de TikTok en directo. ON/OFF a la derecha activa la plataforma.",
        "takeyourstreamchat.config.chat_connection": "Chat en vivo:",
        "takeyourstreamchat.config.chat_connection.desc": "Conectar o desconectar todas las plataformas activadas (como el atajo)",
        "takeyourstreamchat.config.chat_toggle_on": "Chat ON",
        "takeyourstreamchat.config.chat_toggle_off": "Chat OFF",
        "takeyourstreamchat.config.auto_connect_irc": "Auto-conectar al entrar:",
        "takeyourstreamchat.config.auto_connect_irc.desc": "Conectar automáticamente al entrar en mundo/servidor",
        "takeyourstreamchat.config.message_lifetime.desc": "Tiempo visible de los mensajes (en ticks)",
        "takeyourstreamchat.config.message_fall.desc": "Tiempo de caída de los mensajes (en ticks)",
        "takeyourstreamchat.config.message_sound": "Sonido de mensaje nuevo:",
        "takeyourstreamchat.config.message_sound.desc": "Reproducir sonido al aparecer un mensaje",
        "takeyourstreamchat.config.message_sound_volume": "Volumen de notificación (0–1):",
        "takeyourstreamchat.config.message_sound_volume.desc": "Volumen del sonido de notificación",
        "takeyourstreamchat.config.color_emojis": "Emojis a color:",
        "takeyourstreamchat.config.color_emojis.desc": "Mostrar emojis Unicode con la fuente del sistema en lugar de Minecraft",
        "takeyourstreamchat.config.click_to_remove": "Clic para eliminar:",
        "takeyourstreamchat.config.click_to_remove.desc": "Clic izquierdo elimina el mensaje al instante (con partículas)",
        "takeyourstreamchat.config.unpin_mode": "Desfijar mensaje:",
        "takeyourstreamchat.config.unpin_mode.desc": "Desfijar mensaje 3D con clic derecho. «Mensaje completo»: clic corto desfija, mantener arrastra",
        "takeyourstreamchat.config.unpin_mode.pin_icon": "Solo icono de pin",
        "takeyourstreamchat.config.unpin_mode.whole_message": "Mensaje completo",
        "takeyourstreamchat.status.connecting": "Conectando a %s: %s...",
        "takeyourstreamchat.status.connected_count": "Conectado: %s plataforma(s)",
        "takeyourstreamchat.status.no_platforms": "No hay plataformas activadas en ajustes",
        "takeyourstreamchat.status.disconnected": "Chat desconectado",
        "takeyourstreamchat.status.not_connected": "No conectado al chat",
        "takeyourstreamchat.status.offline_one": "%s: %s — sin directo",
        "takeyourstreamchat.status.offline_platform": "%s — sin directo",
        "takeyourstreamchat.status.offline_many": "Sin directo: %s",
        "takeyourstreamchat.status.offline_count": "Plataformas sin directo: %s",
        "takeyourstreamchat.chat.connecting": "Conectando al chat de %s '%s'...",
        "takeyourstreamchat.chat.connected_count": "¡Conectado a %s plataforma(s) de chat!",
        "takeyourstreamchat.chat.no_platforms": "No hay plataformas activadas. Activa al menos una.",
        "takeyourstreamchat.chat.disconnected": "Desconectado de todas las plataformas.",
        "takeyourstreamchat.chat.not_connected": "No conectado a ninguna plataforma.",
        "takeyourstreamchat.chat.error.connect": "Error al conectar con %s: %s",
        "takeyourstreamchat.chat.error.generic": "Error de conexión de %s: %s",
        "takeyourstreamchat.chat.error.not_live": "%s: '%s' no está en directo",
        "takeyourstreamchat.chat.error.no_live_room": "%s: no hay directo para '%s' (nombre incorrecto u offline)",
        "takeyourstreamchat.chat.error.no_live_chat": "%s: chat en vivo no disponible para '%s'",
        "takeyourstreamchat.chat.error.user_not_found": "%s: canal '%s' no encontrado",
        "takeyourstreamchat.chat.error.blocked": "%s: solicitud bloqueada por la plataforma, reintentando...",
        "takeyourstreamchat.history.count": "Mensajes en el historial: %s",
        "takeyourstreamchat.history.pinned_count": "Fijados: %s",
        "takeyourstreamchat.history.pinned_empty": "No hay mensajes fijados. Fija uno en el mundo o en el historial.",
        "takeyourstreamchat.history.empty": "Aún no hay mensajes. Conecta un chat para verlos aquí.",
        "takeyourstreamchat.history.scroll_hint": "Desplazar · Clic para acciones",
        "takeyourstreamchat.history.click_for_actions": "Fijar, bloquear o reproducir",
        "takeyourstreamchat.history.action.pin": "Fijar mensaje",
        "takeyourstreamchat.history.action.unpin": "Desfijar",
        "takeyourstreamchat.history.action.block": "Bloquear usuario",
        "takeyourstreamchat.history.action.replay": "Reproducir en el mundo",
        "takeyourstreamchat.history.message_pinned": "Mensaje fijado",
        "takeyourstreamchat.history.message_unpinned": "Mensaje desfijado",
        "takeyourstreamchat.history.message_replayed": "Mensaje reproducido en el mundo",
        "takeyourstreamchat.history.user_blocked": "%s ha sido bloqueado",
        "takeyourstreamchat.history.user_already_blocked": "%s ya está bloqueado",
        "takeyourstreamchat.history.blocked_badge": "[bloq.]",
        "key.takeyourstreamchat.openconfig": "Abrir ajustes de Stream Chat",
        "key.takeyourstreamchat.startandstop": "Conectar / desconectar chat",
        "key.categories.takeyourstreamchat": "Take Your Stream Chat",
    },
    "zh_cn": {
        "takeyourstreamchat.config.title": "Stream Chat 设置",
        "takeyourstreamchat.config.hint_default": "将鼠标悬停在选项上查看说明",
        "takeyourstreamchat.config.message_history_max": "历史记录大小",
        "takeyourstreamchat.config.message_history_max.desc": "聊天历史中保留的最大消息数",
        "takeyourstreamchat.config.spawn_min_distance": "生成最小距离（格）：",
        "takeyourstreamchat.config.spawn_max_distance": "生成最大距离（格）：",
        "takeyourstreamchat.config.spawn_min_distance.desc": "「围绕玩家」和 FOP 模式的最小水平距离（格）",
        "takeyourstreamchat.config.spawn_max_distance.desc": "「围绕玩家」和 FOP 模式的最大水平距离（格）",
        "takeyourstreamchat.config.regexps": "正则表达式",
        "takeyourstreamchat.config.regexps.desc": "打开正则表达式管理",
        "takeyourstreamchat.config.regexps_config": "配置",
        "takeyourstreamchat.config.role_filter": "角色筛选：",
        "takeyourstreamchat.config.role_filter.desc": "仅显示各平台所选角色的消息（Twitch、YouTube、Kick、TikTok）。设为「全部」时普通观众也会显示。",
        "takeyourstreamchat.config.role_filter.all": "全部",
        "takeyourstreamchat.config.role_filter.subscribers": "订阅者",
        "takeyourstreamchat.config.role_filter.vip": "VIP",
        "takeyourstreamchat.config.role_filter.mods": "管理员",
        "takeyourstreamchat.config.role_filter.sub_or_vip": "订阅或 VIP",
        "takeyourstreamchat.config.role_filter.sub_or_mod": "订阅或管理员",
        "takeyourstreamchat.config.username_blocklist": "用户名黑名单：",
        "takeyourstreamchat.config.username_blocklist.desc": "屏蔽指定用户名的消息",
        "takeyourstreamchat.config.blocked_users": "已屏蔽用户",
        "takeyourstreamchat.config.blocked_users.desc": "管理被屏蔽的用户名",
        "takeyourstreamchat.config.blocked_users_config": "配置",
        "takeyourstreamchat.blocked_users.title": "管理屏蔽用户名",
        "takeyourstreamchat.blocked_users.input": "输入用户名",
        "takeyourstreamchat.blocked_users.add": "添加",
        "takeyourstreamchat.regexps.title": "管理正则表达式",
        "takeyourstreamchat.config.twitch_enabled": "Twitch：",
        "takeyourstreamchat.config.twitch_enabled.desc": "连接时包含 Twitch 聊天",
        "takeyourstreamchat.config.youtube_enabled": "YouTube：",
        "takeyourstreamchat.config.youtube_enabled.desc": "连接时包含 YouTube 直播聊天",
        "takeyourstreamchat.config.youtube_channel": "YouTube 频道：",
        "takeyourstreamchat.config.youtube_channel.desc": "直播中的 @handle、视频链接或 11 位视频 ID。右侧 ON/OFF 开关启用该平台。",
        "takeyourstreamchat.config.kick_enabled": "Kick：",
        "takeyourstreamchat.config.kick_enabled.desc": "连接时包含 Kick 聊天",
        "takeyourstreamchat.config.kick_channel": "Kick 频道：",
        "takeyourstreamchat.config.kick_channel.desc": "kick.com/username 中的频道 slug。右侧 ON/OFF 开关启用该平台。",
        "takeyourstreamchat.config.tiktok_enabled": "TikTok：",
        "takeyourstreamchat.config.tiktok_enabled.desc": "连接时包含 TikTok 直播聊天",
        "takeyourstreamchat.config.tiktok_username": "TikTok 用户名：",
        "takeyourstreamchat.config.tiktok_username.desc": "直播中的 TikTok @username。右侧 ON/OFF 开关启用该平台。",
        "takeyourstreamchat.config.chat_connection": "直播聊天：",
        "takeyourstreamchat.config.chat_connection.desc": "连接或断开所有已启用的平台（与快捷键相同）",
        "takeyourstreamchat.config.chat_toggle_on": "聊天 开",
        "takeyourstreamchat.config.chat_toggle_off": "聊天 关",
        "takeyourstreamchat.config.auto_connect_irc": "进入世界时自动连接：",
        "takeyourstreamchat.config.auto_connect_irc.desc": "进入世界/服务器时自动连接已启用的聊天平台",
        "takeyourstreamchat.config.message_lifetime.desc": "消息可见时长（刻）",
        "takeyourstreamchat.config.message_fall.desc": "消息下落时长（刻）",
        "takeyourstreamchat.config.message_sound": "新消息提示音：",
        "takeyourstreamchat.config.message_sound.desc": "出现新聊天消息时播放提示音",
        "takeyourstreamchat.config.message_sound_volume": "通知音量（0–1）：",
        "takeyourstreamchat.config.message_sound_volume.desc": "新消息提示音的音量",
        "takeyourstreamchat.config.color_emojis": "彩色表情：",
        "takeyourstreamchat.config.color_emojis.desc": "使用系统彩色表情字体渲染 Unicode 表情，而非 Minecraft 字体",
        "takeyourstreamchat.config.click_to_remove": "点击移除：",
        "takeyourstreamchat.config.click_to_remove.desc": "左键点击可立即移除消息（带粒子效果）",
        "takeyourstreamchat.config.unpin_mode": "取消固定：",
        "takeyourstreamchat.config.unpin_mode.desc": "右键取消固定 3D 消息。「整条消息」：短按取消固定，长按拖动",
        "takeyourstreamchat.config.unpin_mode.pin_icon": "仅图钉图标",
        "takeyourstreamchat.config.unpin_mode.whole_message": "整条消息",
        "takeyourstreamchat.status.connecting": "正在连接 %s：%s...",
        "takeyourstreamchat.status.connected_count": "已连接：%s 个平台",
        "takeyourstreamchat.status.no_platforms": "设置中未启用任何平台",
        "takeyourstreamchat.status.disconnected": "聊天已断开",
        "takeyourstreamchat.status.not_connected": "未连接到聊天",
        "takeyourstreamchat.status.offline_one": "%s：%s — 未开播",
        "takeyourstreamchat.status.offline_platform": "%s — 未开播",
        "takeyourstreamchat.status.offline_many": "未开播：%s",
        "takeyourstreamchat.status.offline_count": "未开播平台：%s",
        "takeyourstreamchat.chat.connecting": "正在连接 %s 聊天「%s」...",
        "takeyourstreamchat.chat.connected_count": "已连接 %s 个聊天平台！",
        "takeyourstreamchat.chat.no_platforms": "未启用任何平台。请在设置中至少启用一个。",
        "takeyourstreamchat.chat.disconnected": "已断开所有聊天平台。",
        "takeyourstreamchat.chat.not_connected": "未连接到任何聊天平台。",
        "takeyourstreamchat.chat.error.connect": "连接 %s 时出错：%s",
        "takeyourstreamchat.chat.error.generic": "%s 连接错误：%s",
        "takeyourstreamchat.chat.error.not_live": "%s：「%s」当前未开播",
        "takeyourstreamchat.chat.error.no_live_room": "%s：未找到「%s」的直播（名称错误或已下播）",
        "takeyourstreamchat.chat.error.no_live_chat": "%s：「%s」的直播聊天不可用",
        "takeyourstreamchat.chat.error.user_not_found": "%s：未找到频道「%s」",
        "takeyourstreamchat.chat.error.blocked": "%s：请求被平台拦截，正在重试...",
        "takeyourstreamchat.history.count": "历史消息数：%s",
        "takeyourstreamchat.history.pinned_count": "已固定：%s",
        "takeyourstreamchat.history.pinned_empty": "暂无固定消息。在世界或历史中固定一条即可在此查看。",
        "takeyourstreamchat.history.empty": "暂无消息。连接聊天后即可在此查看。",
        "takeyourstreamchat.history.scroll_hint": "滚动 · 点击消息进行操作",
        "takeyourstreamchat.history.click_for_actions": "固定、屏蔽或重播",
        "takeyourstreamchat.history.action.pin": "固定消息",
        "takeyourstreamchat.history.action.unpin": "取消固定",
        "takeyourstreamchat.history.action.block": "屏蔽用户",
        "takeyourstreamchat.history.action.replay": "在世界中重播",
        "takeyourstreamchat.history.message_pinned": "消息已固定",
        "takeyourstreamchat.history.message_unpinned": "消息已取消固定",
        "takeyourstreamchat.history.message_replayed": "消息已在世界中重播",
        "takeyourstreamchat.history.user_blocked": "已屏蔽 %s",
        "takeyourstreamchat.history.user_already_blocked": "%s 已在黑名单中",
        "takeyourstreamchat.history.blocked_badge": "[已屏蔽]",
        "key.takeyourstreamchat.openconfig": "打开 Stream Chat 设置",
        "takeyourstreamchat.startandstop": "连接 / 断开聊天",
        "key.takeyourstreamchat.startandstop": "连接 / 断开聊天",
        "key.categories.takeyourstreamchat": "Take Your Stream Chat",
    },
    "ru_ru": {
        "key.takeyourstreamchat.openconfig": "Открыть настройки Stream Chat",
        "takeyourstreamchat.history.empty": "Сообщений пока нет. Подключите чат любой платформы, чтобы увидеть их здесь.",
    },
}


def merge_locale(locale: str) -> dict[str, str]:
    en = json.loads((LANG_DIR / "en_us.json").read_text(encoding="utf-8"))
    path = LANG_DIR / f"{locale}.json"
    existing: dict[str, str] = {}
    if path.exists():
        text = path.read_text(encoding="utf-8")
        existing = json.loads(text)
    overrides = OVERRIDES.get(locale, {})
    merged: dict[str, str] = {}
    for key in en:
        merged[key] = overrides.get(key) or existing.get(key) or en[key]
    return merged


def main() -> None:
    en = json.loads((LANG_DIR / "en_us.json").read_text(encoding="utf-8"))
    en_keys = set(en)
    for locale in ["de_de", "es_es", "fr_fr", "zh_cn", "ru_ru"]:
        merged = merge_locale(locale)
        missing = en_keys - set(merged)
        if missing:
            raise SystemExit(f"{locale} still missing keys: {sorted(missing)}")
        path = LANG_DIR / f"{locale}.json"
        path.write_text(json.dumps(merged, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {locale}.json ({len(merged)} keys)")


if __name__ == "__main__":
    main()
